#! /bin/sh

setxkbmap -layout 'us,ru' -option 'grp:win_space_toggle' &
pgrep -x sxhkd > /dev/null || sxhkd &

pipewire &
wireplumber &
polybar &
mako &
feh --bg-scale /home/nikhil/Pictures/Wallpapers/Tree.png

bspc monitor -d 1 2 3 4 5

bspc config border_width         3
bspc config window_gap          10

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
