#!/usr/bin/env sh

user="$USER"
riverctl focused-output riverctl spawn 'wl-paste --watch-clipboard -n text'
riverctl input-layout us,ru
riverctl input-option xkb-options grp:win_space_toggle
riverctl border-width 3
riverctl border-color-focused cba6f7 cba6f7 cba6f7
riverctl border-color-unfocused 6c7086 6c7086 6c7086
riverctl border-radius 0
riverctl default-layout rivertile
riverctl xcursor-theme leftptr 24


pipewire &
pipewire-pulse &
wireplumber &
polybar &
mako &
feh --bg-scale ~/Pictures/Wallpapers/images.png &
nm-applet &
flameshot &


riverctl map normal Super Return spawn alacritty
riverctl map normal Super W spawn waterfox
riverctl map normal Super O spawn obsidian
riverctl map normal Super C spawn vscodium
riverctl map normal Super T spawn TelegramDesktop
riverctl map normal Super Q close
riverctl map normal Super E spawn nemo
riverctl map normal Super D spawn "rofi -show drun"
riverctl map normal Super A spawn pavucontrol


riverctl map normal Super J focus-view next
riverctl map normal Super K focus-view previous
riverctl map normal Super Left focus-view left
riverctl map normal Super Right focus-view right
riverctl map normal Super Up focus-view up
riverctl map normal Super Down focus-view down


for i in $(seq 1 9); do
riverctl map normal Super $i set-focused-tags $((1 << ($i - 1)))
riverctl map normal Super Shift $i set-view-tags $((1 << ($i - 1)))
done
riverctl map normal Super 0 set-focused-tags 1023 # Все теги


riverctl map normal Super Alt Left swap next left
riverctl map normal Super Alt Right swap next right
riverctl map normal Super Alt Up swap next up
riverctl map normal Super Alt Down swap next down


riverctl map normal Super F toggle-float


riverctl map normal Super Shift Right resize-view 30 0
riverctl map normal Super Shift Left resize-view -30 0
riverctl map normal Super Shift Up resize-view 0 -30
riverctl map normal Super Shift Down resize-view 0 30


riverctl map normal Super Escape send-layout-msg rivertile resizeview


riverctl map normal Super L spawn swaylock # или hyprlock если есть
riverctl map normal Super P spawn 'grim -g "$(slurp)" - | wl-copy'
riverctl map normal Super Shift P spawn grim -t output - | wl-copy


riverctl map normal XF86AudioRaiseVolume exec pamixer -i 5
riverctl map normal XF86AudioLowerVolume exec pamixer -d 5
riverctl map normal XF86AudioMute exec pamixer -t
riverctl map normal XF86MonBrightnessUp exec brightnessctl s +5%
riverctl map normal XF86MonBrightnessDown exec brightnessctl s 5%


riverctl rule-add -app-id pavucontrol float
riverctl rule-add -app-id nwg-look float
riverctl rule-add -app-id nm-applet float
riverctl rule-add -app-id blueman-manager float
riverctl rule-add -app-id org.kde.ark float


riverctl set-pointer-cursor leftptr 24
riverctl pointer-button Super 1 move-view
riverctl pointer-button Super 2 resize-view

riverctl spawn 'rivertile -view-padding 10 -outer-padding 10'
